#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'rubygems' unless defined?(Gem)
require 'lib/vmpooler'

Thread.new { Vmpooler::API.new.execute! }
Thread.new { Vmpooler::PoolManager.new.execute! }

loop do
  sleep(10)
end
